### ISSUE TITLE
syntax errors

### ISSUE THREAD

**Issue by beugen7171** [learn-co-curriculum/ruby-lecture-reading-error-messages#22]
when typing / defining to ruby that  x = 1 and then trying to write x = 2 on another line, how is it not a error ? how can you have x defined as 1 and or 2 ?

**Comment by JessRudder** [comment]
@beugen7171 You are correct that a variable cannot be both values at once.

In this case, Ruby is reading the file line by line.

On the first line, when you write ```x = 1``` if you check the value of x it will be 1.

After the next line of code ```x = 2```, the value of x has been changed.  Now, if you check x, it will be 2.

There's no syntax error because you are allowed to reassign variables in Ruby.

**Comment by beugen7171** [comment]
Weird, I knew the answer to that.  Must of asked out loud  :).
