### ISSUE TITLE
I am completely lost

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/ruby-lecture-reading-error-messages#27]
I have followed all the directions and it is not doing what the instructions say should happen. This is making me frustrated. I would still like to learn but if it is going to continue to not work I will stop.

**Comment by AnnJohn** [comment]
Hi @ghost. Sorry for the frustration, but please use the Ask a Question tool in Learn and someone from our support team will get back to you right away. We understand that learning is difficult and often can be very very frustrating and so, rather than make it easier, we make it very easy for you to get support. Definitely use the Ask a Question tool if you ever have any questions about how to solve a lab or if you have questions about any concepts. Thanks!
