### ISSUE TITLE
No files 

### ISSUE THREAD

**Issue by Ramseycj12** [learn-co-curriculum/ruby-lecture-reading-error-messages#36]
I dont see and files populating in the directory for me to be able to go in and fix the errors! 

![screen shot 2016-05-28 at 9 19 38 am](https://cloud.githubusercontent.com/assets/19617316/15627533/52df13b2-24b5-11e6-8e36-a1424504419f.png)

**Comment by AnnJohn** [comment]
hi @Ramseycj12 sorry for this issue and the delay. This is a technical issue so could you please file a bug report? If you hover over your profile pic in Learn, you'll see an option to Report a Bug. 

Also please use the Ask a Question tool so that someone from our Learn Expert team can help you resolve this issue if you haven't done so already. Thanks!
